#ifndef DAQPIPELINESTAGES_GLOBAL_H
#define DAQPIPELINESTAGES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DAQPIPELINESTAGES_LIBRARY)
#  define DAQPIPELINESTAGESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DAQPIPELINESTAGESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DAQPIPELINESTAGES_GLOBAL_H
