#ifndef SIGNALPROCESSINGPIPELINESTAGES_GLOBAL_H
#define SIGNALPROCESSINGPIPELINESTAGES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIGNALPROCESSINGPIPELINESTAGES_LIBRARY)
#  define SIGNALPROCESSINGPIPELINESTAGESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIGNALPROCESSINGPIPELINESTAGESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALPROCESSINGPIPELINESTAGES_GLOBAL_H
