#ifndef PROCESSINGPIPELINESTAGES_GLOBAL_H
#define PROCESSINGPIPELINESTAGES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PROCESSINGPIPELINESTAGES_LIBRARY)
#  define PROCESSINGPIPELINESTAGESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PROCESSINGPIPELINESTAGESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PROCESSINGPIPELINESTAGES_GLOBAL_H
