#ifndef PERIPHERAL_GLOBAL_H
#define PERIPHERAL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PERIPHERAL_LIBRARY)
#  define PERIPHERALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PERIPHERALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PERIPHERAL_GLOBAL_H
