#ifndef DISPLAYPIPELINESTAGE_GLOBAL_H
#define DISPLAYPIPELINESTAGE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DISPLAYPIPELINESTAGE_LIBRARY)
#  define DISPLAYPIPELINESTAGESHARED_EXPORT Q_DECL_EXPORT
#else
#  define DISPLAYPIPELINESTAGESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DISPLAYPIPELINESTAGE_GLOBAL_H
